In [6]:
from dl_assignment_2.data.data_config import INTRA_TRAIN
from dl_assignment_2.data.dataSegment import DataSegment

import numpy as np

indirect_path: str = f"{INTRA_TRAIN}/rest_105923_1.h5"

x = DataSegment(indirect_path)



In [7]:
y = x.transform(lambda x: x*0)
np.all(y.data)

np.False_

In [8]:
3//5

0

In [9]:
35624//13

2740

In [11]:
y = x.trim(13)
y.data.shape

(248, 32883)

In [23]:
a = np.array([[1,2,3,4], [1,2,3,4], [1,2,3,4]])
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [25]:
np.delete(a, [0,2], 1)

array([[2, 4],
       [2, 4],
       [2, 4]])

In [21]:
b = np.array([1,2,3,4,5,6,7,8,9])

np.delete(b,[1,3])

array([1, 3, 5, 6, 7, 8, 9])

In [39]:
step: int = 3
indices_to_delete = np.array(range(0,len(b)-1, step))+1
indices_to_delete

array([1, 4, 7])

In [ ]:
step: int = 3
def compute_indices_to_keep(b, step) -> list[int]:
    start = step-1
    indices_to_keep = [start]

    s = 1
    while indices_to_keep[-1] < len(b):
        indices_to_keep.append(start + step*s)
        s+=1
    indices_to_keep.pop()

    indices_to_keep

compute_indices_to_keep(step)



[2, 5, 8]

In [ ]:
def compute_indices_to_remove(b, indices_to_keep):
    return list(set(range(len(b))).difference(indices_to_keep))

indices_to_remove = compute_indices_to_remove()
indices_to_remove

[0, 1, 3, 4, 6, 7]

In [62]:
np.delete(b, indices_to_remove)

array([3, 6, 9])

In [ ]:
def trim(data: np.ndarray, n: int = 3) -> np.ndarray:
    kept_indices: list[int] = compute_indices_to_keep(data, n)

    removed_indices: list[int] = compute_indices_to_remove(data, kept_indices)

    if len(data.shape) == 2:
        return np.delete(data, removed_indices, 1)

    else:
        return np.delete(data, removed_indices)


